FROM ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update \
    && apt-get install -y python3 python3-pip 

WORKDIR /app

COPY 1/requirements.txt .

RUN python3 -m pip install --no-cache-dir -r requirements.txt

COPY 1/httpcode.py .

CMD ["python3", "httpcode.py"]